export type CatalogRecord = { id:string; observed_month:string; region_key:string; region_name:string; sport_key:string; sport_name:string; facility_name:string; facility_address:string; course_name:string; target_disability_note:string|null; price_krw:number; cap_krw?:number; course_begin_date:string; course_end_date:string; date_overlaps_observed_month:boolean; boundary_mapping_status:string }
export type Catalog={schema_version:string;observed_month:string;cap_krw:number;application_status:string;records:CatalogRecord[]}
export type MonthMeta={month:string;priced_records:number;date_overlapping_records:number;under_cap_date_overlapping_records:number;selected_courses_with_same_region_price_partner:number;regions_with_price_partner:number}
export type Meta={schema_version:string;observed_through:string;default_catalog_month:string;available_catalog_months:MonthMeta[];latest_month_low_volume_review:boolean;latest_month_note:string}
export type Region={region_key:string;region_name:string;sido_code:string};export type Sport={sport_key:string;sport_name:string};export type Lookups={regions:Region[];sports:Sport[]}
export type MapRecord={region_key:string;sport_key:string;denominator:number;at_cap_count:number;at_cap_ratio:number;below_cap_count:number;over_cap_count:number;price_median_krw:number;small_sample:boolean;mapping_status:string;observed_from:string;observed_through:string;cap_krw:number|null;cap_min_krw:number;cap_max_krw:number}
export type MapDocument={schema_version:string;period:string;unit:string;records:MapRecord[]};export type BinGroup={region_key:string;sport_key:string;denominator:number;price_bins:[number,number][]};export type BinDocument={schema_version:string;period:string;unit:string;base_cap_krw:number;groups:BinGroup[]}
export type History={schema_version:string;national:Record<string,{denominator:number;numerator_at_cap:number;ratio_at_cap:number;cap_krw:number|null}>;same_id_2023_2024:{same_id_count:number;unchanged:number;up:number;down:number;entry_ids_2024:number;exit_ids_2023:number;note:string};unique_course_cohorts_2023_2024:{year:string;cohort:string;course_ids:number;positive_price_ids:number;at_110k_ids:number;at_110k_share:number}[];interpretation:string}
export type Companion=CatalogRecord&{combined_price_krw:number;remaining_cap_after_pair_krw:number};export type CompanionResult={selected:CatalogRecord;cap_krw:number;planning_headroom_krw:number;total_candidates:number;candidates:Companion[];reason:string|null}
export type SimulationResult={status:'ok';period:string;unit:string;region_key:string;sport_key:string;base_cap_krw:number;target_cap_krw:number;compared_records:number;baseline_eligible_count:number;scenarios:{key:'freeze'|'half'|'full';assumed_price_increase_krw:number;eligible_count:number;newly_eligible_count:number;at_new_cap_count:number;compared_records:number}[];interpretation:string}|{status:'no_records';region_key:string;sport_key:string}
